[autolabel."wontfix"]
trigger_labels = [
  "bug"
]

[autolabel."invalid"]
new_issue = true

[autolabel."documentation"]
new_pr = true

[autolabel."help wanted"]
new_pr = truedfdfdfd
new_issue = true
exclude_labels = ["duplicate"]
